---
  extends:
    - 'airbnb-base'
    - 'plugin:jest/recommended'

  parser: babel-eslint

  plugins:
  - jest
  - babel

  env:
    node: true
    jest: true

  rules:
    no-console: 0
    jest/expect-expect:
      - error
      - assertFunctionNames:
        - assert.strictEqual